version: '3.8'

services:

  service:
    build:
        dockerfile: ./service/Dockerfile
        context: .
    ports:
      - 5000:5000
    volumes:
      - ./service:/app
    networks:
    - minha-network
    restart: on-failure

  frontend:
    build:
        dockerfile: ./Dockerfile
        context: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    networks:
    - minha-network
    restart: on-failure


  keycloak:
    image: quay.io/keycloak/keycloak:18.0.1
    container_name: keycloak
    command:
      - "start-dev"
    ports:
      - 8081:8080
    expose:
      - 8081
    environment:
        KEYCLOAK_ADMIN : admin
        KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
    - minha-network
    restart: on-failure
    volumes:
      - keycloak_data:/opt/keycloak/data/

volumes:
  keycloak_data:

networks:
  minha-network:
    driver: "bridge"